# Generated by Django 2.2.5 on 2019-09-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190911_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='upc',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
