export const StoreActions = {
    // Category
    CREATE_CATEGORY: "CREATE_CATEGORY",
    UPDATE_CATEGORY: "UPDATE_CATEGORY",
    DELETE_CATEGORY: "DELETE_CATEGORY",
    FETCH_CATEGORIES: "FETCH_CATEGORIES",
}