export const StoreActions = {
  // Category
  CREATE_CATEGORY: "CREATE_CATEGORY",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  FETCH_CATEGORIES: "FETCH_CATEGORIES",

  // Unit Of Measure
  CREATE_UNIT: "CREATE_UNIT",
  UPDATE_UNIT: "UPDATE_UNIT",
  DELETE_UNIT: "DELETE_UNIT",
  FETCH_UNITS: "FETCH_UNITS",

  // Product
  CREATE_PRODUCT: "CREATE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  FETCH_PRODUCTS: "FETCH_PRODUCTS",

  // Service
  CREATE_SERVICE: "CREATE_SERVICE",
  UPDATE_SERVICE: "UPDATE_SERVICE",
  DELETE_SERVICE: "DELETE_SERVICE",
  FETCH_SERVICES: "FETCH_SERVICES"
};
