export const StoreActions = {
    // Category
    CREATE_CATEGORY: "CREATE_CATEGORY",
    UPDATE_CATEGORY: "UPDATE_CATEGORY",
    DELETE_CATEGORY: "DELETE_CATEGORY",
    FETCH_CATEGORIES: "FETCH_CATEGORIES",

    // Unit Of Measure
    CREATE_UNIT: "CREATE_UNIT",
    UPDATE_UNIT: "UPDATE_UNIT",
    DELETE_UNIT: "DELETE_UNIT",
    FETCH_UNITS: "FETCH_UNITS",
}